#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaf.Repository.LinqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="YAF")]
	public partial class YafDatabase : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public YafDatabase() : 
				base(global::Yaf.Properties.Settings.Default.YAFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public YafDatabase(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public YafDatabase(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public YafDatabase(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public YafDatabase(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.yafGetRecentPosts")]
		public ISingleResult<Yaf.Concrete.yafGetRecentPostsResult> yafGetRecentPosts()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Yaf.Concrete.yafGetRecentPostsResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.yafGetUserId")]
		public ISingleResult<Yaf.Concrete.yafGetUserIdResult> yafGetUserId([Parameter(Name="YafUserId", DbType="Int")] System.Nullable<int> yafUserId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yafUserId);
			return ((ISingleResult<Yaf.Concrete.yafGetUserIdResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.yafGetRecentTopics")]
		public ISingleResult<Yaf.Concrete.yafGetRecentTopicsResult> yafGetRecentTopics()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Yaf.Concrete.yafGetRecentTopicsResult>)(result.ReturnValue));
		}
	}
}
namespace Yaf.Concrete
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	public partial class yafGetRecentPostsResult
	{
		
		private int _MessageID;
		
		private int _TopicID;
		
		private System.Nullable<int> _ReplyTo;
		
		private int _Position;
		
		private int _Indent;
		
		private int _UserID;
		
		private string _UserName;
		
		private System.DateTime _Posted;
		
		private string _Message;
		
		private string _IP;
		
		private System.Nullable<System.DateTime> _Edited;
		
		private int _Flags;
		
		private string _EditReason;
		
		private bool _IsModeratorChanged;
		
		private string _DeleteReason;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<bool> _IsApproved;
		
		private string _BlogPostID;
		
		public yafGetRecentPostsResult()
		{
		}
		
		[Column(Storage="_MessageID", DbType="Int NOT NULL")]
		public int MessageID
		{
			get
			{
				return this._MessageID;
			}
			set
			{
				if ((this._MessageID != value))
				{
					this._MessageID = value;
				}
			}
		}
		
		[Column(Storage="_TopicID", DbType="Int NOT NULL")]
		public int TopicID
		{
			get
			{
				return this._TopicID;
			}
			set
			{
				if ((this._TopicID != value))
				{
					this._TopicID = value;
				}
			}
		}
		
		[Column(Storage="_ReplyTo", DbType="Int")]
		public System.Nullable<int> ReplyTo
		{
			get
			{
				return this._ReplyTo;
			}
			set
			{
				if ((this._ReplyTo != value))
				{
					this._ReplyTo = value;
				}
			}
		}
		
		[Column(Storage="_Position", DbType="Int NOT NULL")]
		public int Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[Column(Storage="_Indent", DbType="Int NOT NULL")]
		public int Indent
		{
			get
			{
				return this._Indent;
			}
			set
			{
				if ((this._Indent != value))
				{
					this._Indent = value;
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[Column(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[Column(Storage="_Posted", DbType="DateTime NOT NULL")]
		public System.DateTime Posted
		{
			get
			{
				return this._Posted;
			}
			set
			{
				if ((this._Posted != value))
				{
					this._Posted = value;
				}
			}
		}
		
		[Column(Storage="_Message", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[Column(Storage="_IP", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this._IP = value;
				}
			}
		}
		
		[Column(Storage="_Edited", DbType="DateTime")]
		public System.Nullable<System.DateTime> Edited
		{
			get
			{
				return this._Edited;
			}
			set
			{
				if ((this._Edited != value))
				{
					this._Edited = value;
				}
			}
		}
		
		[Column(Storage="_Flags", DbType="Int NOT NULL")]
		public int Flags
		{
			get
			{
				return this._Flags;
			}
			set
			{
				if ((this._Flags != value))
				{
					this._Flags = value;
				}
			}
		}
		
		[Column(Storage="_EditReason", DbType="NVarChar(100)")]
		public string EditReason
		{
			get
			{
				return this._EditReason;
			}
			set
			{
				if ((this._EditReason != value))
				{
					this._EditReason = value;
				}
			}
		}
		
		[Column(Storage="_IsModeratorChanged", DbType="Bit NOT NULL")]
		public bool IsModeratorChanged
		{
			get
			{
				return this._IsModeratorChanged;
			}
			set
			{
				if ((this._IsModeratorChanged != value))
				{
					this._IsModeratorChanged = value;
				}
			}
		}
		
		[Column(Storage="_DeleteReason", DbType="NVarChar(100)")]
		public string DeleteReason
		{
			get
			{
				return this._DeleteReason;
			}
			set
			{
				if ((this._DeleteReason != value))
				{
					this._DeleteReason = value;
				}
			}
		}
		
		[Column(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[Column(Storage="_IsApproved", DbType="Bit")]
		public System.Nullable<bool> IsApproved
		{
			get
			{
				return this._IsApproved;
			}
			set
			{
				if ((this._IsApproved != value))
				{
					this._IsApproved = value;
				}
			}
		}
		
		[Column(Storage="_BlogPostID", DbType="NVarChar(50)")]
		public string BlogPostID
		{
			get
			{
				return this._BlogPostID;
			}
			set
			{
				if ((this._BlogPostID != value))
				{
					this._BlogPostID = value;
				}
			}
		}
	}
	
	public partial class yafGetUserIdResult
	{
		
		private string _ProviderUserKey;
		
		public yafGetUserIdResult()
		{
		}
		
		[Column(Storage="_ProviderUserKey", DbType="NVarChar(64)")]
		public string ProviderUserKey
		{
			get
			{
				return this._ProviderUserKey;
			}
			set
			{
				if ((this._ProviderUserKey != value))
				{
					this._ProviderUserKey = value;
				}
			}
		}
	}
	
	public partial class yafGetRecentTopicsResult
	{
		
		private int _TopicID;
		
		private int _ForumID;
		
		private int _UserID;
		
		private string _UserName;
		
		private System.DateTime _Posted;
		
		private string _Topic;
		
		private int _Views;
		
		private short _Priority;
		
		private System.Nullable<int> _PollID;
		
		private System.Nullable<int> _TopicMovedID;
		
		private System.Nullable<System.DateTime> _LastPosted;
		
		private System.Nullable<int> _LastMessageID;
		
		private System.Nullable<int> _LastUserID;
		
		private string _LastUserName;
		
		private int _NumPosts;
		
		private int _Flags;
		
		private System.Nullable<bool> _IsDeleted;
		
		public yafGetRecentTopicsResult()
		{
		}
		
		[Column(Storage="_TopicID", DbType="Int NOT NULL")]
		public int TopicID
		{
			get
			{
				return this._TopicID;
			}
			set
			{
				if ((this._TopicID != value))
				{
					this._TopicID = value;
				}
			}
		}
		
		[Column(Storage="_ForumID", DbType="Int NOT NULL")]
		public int ForumID
		{
			get
			{
				return this._ForumID;
			}
			set
			{
				if ((this._ForumID != value))
				{
					this._ForumID = value;
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[Column(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[Column(Storage="_Posted", DbType="DateTime NOT NULL")]
		public System.DateTime Posted
		{
			get
			{
				return this._Posted;
			}
			set
			{
				if ((this._Posted != value))
				{
					this._Posted = value;
				}
			}
		}
		
		[Column(Storage="_Topic", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Topic
		{
			get
			{
				return this._Topic;
			}
			set
			{
				if ((this._Topic != value))
				{
					this._Topic = value;
				}
			}
		}
		
		[Column(Storage="_Views", DbType="Int NOT NULL")]
		public int Views
		{
			get
			{
				return this._Views;
			}
			set
			{
				if ((this._Views != value))
				{
					this._Views = value;
				}
			}
		}
		
		[Column(Storage="_Priority", DbType="SmallInt NOT NULL")]
		public short Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
		
		[Column(Storage="_PollID", DbType="Int")]
		public System.Nullable<int> PollID
		{
			get
			{
				return this._PollID;
			}
			set
			{
				if ((this._PollID != value))
				{
					this._PollID = value;
				}
			}
		}
		
		[Column(Storage="_TopicMovedID", DbType="Int")]
		public System.Nullable<int> TopicMovedID
		{
			get
			{
				return this._TopicMovedID;
			}
			set
			{
				if ((this._TopicMovedID != value))
				{
					this._TopicMovedID = value;
				}
			}
		}
		
		[Column(Storage="_LastPosted", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastPosted
		{
			get
			{
				return this._LastPosted;
			}
			set
			{
				if ((this._LastPosted != value))
				{
					this._LastPosted = value;
				}
			}
		}
		
		[Column(Storage="_LastMessageID", DbType="Int")]
		public System.Nullable<int> LastMessageID
		{
			get
			{
				return this._LastMessageID;
			}
			set
			{
				if ((this._LastMessageID != value))
				{
					this._LastMessageID = value;
				}
			}
		}
		
		[Column(Storage="_LastUserID", DbType="Int")]
		public System.Nullable<int> LastUserID
		{
			get
			{
				return this._LastUserID;
			}
			set
			{
				if ((this._LastUserID != value))
				{
					this._LastUserID = value;
				}
			}
		}
		
		[Column(Storage="_LastUserName", DbType="NVarChar(50)")]
		public string LastUserName
		{
			get
			{
				return this._LastUserName;
			}
			set
			{
				if ((this._LastUserName != value))
				{
					this._LastUserName = value;
				}
			}
		}
		
		[Column(Storage="_NumPosts", DbType="Int NOT NULL")]
		public int NumPosts
		{
			get
			{
				return this._NumPosts;
			}
			set
			{
				if ((this._NumPosts != value))
				{
					this._NumPosts = value;
				}
			}
		}
		
		[Column(Storage="_Flags", DbType="Int NOT NULL")]
		public int Flags
		{
			get
			{
				return this._Flags;
			}
			set
			{
				if ((this._Flags != value))
				{
					this._Flags = value;
				}
			}
		}
		
		[Column(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
